version: "3"

services:
  healthcheck:
    image: healthcheck:v1
    container_name: app
    expose:
      - 5000
    ports:
      - "5000:5000"
    environment: 
      - MYSQL_HOST=db
      - MYSQL_PASSWORD=
      - MYSQL_USER=root
      - MYSQL_DATABASE=web_chat
      - MYSQL_PORT=3306
      - REDIS_PORT=6379
      - REDIS_HOST=redis
      - PORT=5000
    depends_on: 
      - db
      - redis
    restart: on-failure
  
  db:
    image: mysql:5.7
    container_name: storage
    expose:
      - 3306
    ports:
      - "3306:3306"
    environment: 
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_PASSWORD=
      - MYSQL_USER=root
      - MYSQL_DATABASE=web_chat
      # - DATABASE_HOST=db
    volumes: 
      - ./dbdata:/docker-entrypoint-initdb.d
    restart: always
  
  redis:
    image: redis
    container_name: cache
    expose: 
      - 6379
    ports: 
      - "6379:6379"